[profile.default]
src = 'contracts'
test = 'foundry/test'
out = 'foundry/out'
libs = ['lib', 'node_modules']
fs_permissions = [{ access = "read", path = "node_modules" }]
cache = true
optimizer = true
optimizer_runs = 200
auto_detect_solc = true
evm_version = 'cancun'
via_ir = true
remappings = [
  '@openzeppelin/=node_modules/@openzeppelin/',
  '@uniswap/v3-core/=node_modules/@uniswap/v3-core/',
  '@uniswap/v3-periphery/=node_modules/@uniswap/v3-periphery/',
  '@uniswap/v4-core/=node_modules/@uniswap/v4-core/',
  '@uniswap/v4-periphery/=node_modules/@uniswap/v4-periphery/',
  '@nomicfoundation/=node_modules/@nomicfoundation/',
  'hardhat/=node_modules/hardhat/',
  'forge-std/=lib/forge-std/src/',
  'solmate/=lib/solmate/'
]

[rpc_endpoints]
base = '${BASE_RPC_URL}'
base_testnet = '${BASE_TESTNET_RPC_URL}'

[fmt]
line_length = 120
